type User{
    identifier: String!
    bookings: [Booking!] @relation
}

type Venue{
    name: String!
    bookings: [Booking!] @relation
}

type Booking{
    venue: Venue!
    user: User!
}

input UserInput{
    identifier: String!
}

type Query{
    allVenues: [Venue!]!
    findUserByIdentifier(identifier: String!): User
}